#!/bin/bash
#OAR -q production
#OAR -p cluster='grue'
#OAR -l walltime=08:00:00
#OAR -O OUT/oar_job.%jobid%.output
#OAR -E OUT/oar_job.%jobid%.error

source /home/psrivastava/new_env/bin/activate
python /home/psrivastava/axis-2/IWAENC/train_scripts/D1_0000/mlh_baseline.py



